version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 583261726886.dkr.ecr.eu-west-1.amazonaws.com/my-app-repo
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t 583261726886.dkr.ecr.eu-west-1.amazonaws.com/my-app-repo:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker tag 583261726886.dkr.ecr.eu-west-1.amazonaws.com/my-app-repo:$CODEBUILD_RESOLVED_SOURCE_VERSION 583261726886.dkr.ecr.eu-west-1.amazonaws.com/my-app-repo:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 583261726886.dkr.ecr.eu-west-1.amazonaws.com/my-app-repo:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push 583261726886.dkr.ecr.eu-west-1.amazonaws.com/my-app-repo:latest
      - echo Docker image has been pushed successfully.
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
