AWSTemplateFormatVersion: "2010-09-09"
Description: >
  This template deploys a testing CodePipeline with its required resources for a testing environment, including App Runner and ECR access.

Parameters:
  Environment:
    Type: String
    Default: "Testing"
  
  GitBranch:
    Type: String
    Default: "main"
  
  FullRepositoryId:
    Type: String
    Default: "Detectronic/Data-Visualiser"

  CodeStarConnectionArn:
    Type: String
    Default: "arn:aws:codestar-connections:eu-west-1:583261726886:connection/7fba6c00-7d2d-4878-8ac6-13f47013dfa7"

  EcrImageTag:
    Type: String
    Default: "latest"

  VPCId:
    Type: String
    Default: "vpc-0ca52eb6b0f7d03a3"

  PrivateSubnet1:
    Type: String
    Default: "subnet-00c4e4fea393215aa"

  PrivateSubnet2:
    Type: String
    Default: "subnet-083d121cdc5bc5e0c"

  RdsInstanceArn:
    Type: String
    Default: "arn:aws:rds:eu-west-1:583261726886:db:datavis-testing"

  RdsSecurityGroupId:
    Type: String
    Default: "sg-06d609bba3d27ff89"

  SecretKeySecretArn:
    Type: String
    Default: "arn:aws:secretsmanager:eu-west-1:583261726886:secret:DataVisualizer/Secret-Test-iTBotZ"

Resources:
  PipelineArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "data-visualizer-test-pipeline-artifacts"
      VersioningConfiguration:
        Status: Enabled
      LoggingConfiguration:
        DestinationBucketName: !Ref PipelineArtifactsLoggingBucket
        LogFilePrefix: "artifacts-logs"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  PipelineArtifactsLoggingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "data-visualizer-test-pipeline-logs"
      VersioningConfiguration:
        Status: Enabled

  PipelineArtifactsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref PipelineArtifactsBucket
      PolicyDocument:
        Statement:
          - Effect: "Deny"
            Action: "s3:*"
            Principal: "*"
            Resource:
              - !Sub "${PipelineArtifactsBucket.Arn}/*"
              - !GetAtt PipelineArtifactsBucket.Arn
            Condition:
              Bool:
                aws:SecureTransport: false

  CodeBuildProjectPrepareCloudFormation:
    Type: AWS::CodeBuild::Project
    Properties: 
      Name: "DataVisualizerTest-CodeBuildPrepareCloudFormation"
      Artifacts: 
        Type: CODEPIPELINE
      Environment: 
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
      Source: 
        Type: CODEPIPELINE
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Description: "CodeBuild project for preparing CloudFormation templates"

  CodeBuildProjectBuild:
    Type: AWS::CodeBuild::Project
    Properties: 
      Name: "DataVisualizerTest-CodeBuildBuild"
      Artifacts: 
        Type: CODEPIPELINE
      Environment: 
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
      Source: 
        Type: CODEPIPELINE
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Description: "CodeBuild project for building container image"

  AppRunnerServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "DataVisualizerTest-AppRunnerRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: apprunner.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "AppRunnerFullAccess"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - apprunner:*
                  - ecr:*
                  - logs:*
                  - s3:GetObject
                  - s3:PutObject
                  - ec2:Describe*
                Resource: "*"

  AppRunnerService:
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: "DataVisualizerTest-AppRunner"
      SourceConfiguration:
        ImageRepository:
          ImageIdentifier: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${FullRepositoryId}:${EcrImageTag}"
          ImageConfiguration:
            Port: "8080"
          ImageRepositoryType: ECR
        AuthenticationConfiguration:
          AccessRoleArn: !GetAtt AppRunnerServiceRole.Arn
      InstanceConfiguration:
        Cpu: "1024"
        Memory: "2048"
      NetworkConfiguration:
        EgressConfiguration:
          EgressType: VPC
          VpcConnectorArn: !Ref VpcConnector
      HealthCheckConfiguration:
        Protocol: HTTP
        Path: "/health"

  VpcConnector:
    Type: AWS::AppRunner::VpcConnector
    Properties:
      Subnets:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
      SecurityGroups:
        - !Ref RdsSecurityGroupId

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location: !Ref PipelineArtifactsBucket
        Type: S3
      RoleArn: arn:aws:iam::583261726886:role/Data-Visualiser-Test-Role
      RestartExecutionOnUpdate: true
      Stages:
        - Name: Source
          Actions:
            - Name: SourceCodeRepo
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: "1"
              Configuration:
                ConnectionArn: !Ref CodeStarConnectionArn
                FullRepositoryId: !Ref FullRepositoryId
                BranchName: !Ref GitBranch
              OutputArtifacts:
                - Name: SourceCodeAsZip
              RunOrder: 1
        
        - Name: BuildAndDeploy
          Actions:
            - Name: BuildContainerImage
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: SourceCodeAsZip
              Configuration:
                ProjectName: !Ref CodeBuildProjectBuild
              RunOrder: 1
            - Name: PrepareCloudFormation
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              InputArtifacts:
                - Name: SourceCodeAsZip
              OutputArtifacts:
                - Name: AppRunnerCloudFormation
              Configuration:
                ProjectName: !Ref CodeBuildProjectPrepareCloudFormation
              RunOrder: 2

        - Name: AppRunnerDeploy
          Actions:
            - Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              InputArtifacts:
                - Name: AppRunnerCloudFormation
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                RoleArn: arn:aws:iam::583261726886:role/Data-Visualiser-Test-Role
                StackName: !Sub "${AWS::StackName}-AppRunnerService"
                TemplatePath: AppRunnerCloudFormation::template.yml
              RunOrder: 1

  # Other Resources (S3 Buckets, IAM Roles, etc.) remain unchanged.
