name: Deploy CloudFormation Stack to Production

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::507038060985:role/YourDeploymentRole

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --stack-name DataApiRequestLogArchiveBackup-Prod \
            --template-file template.yml \
            --capabilities CAPABILITY_NAMED_IAM
