- name: Deploy to AWS
  run: |
    sam build --template-file pipeline-template.yml
    sam deploy --template-file pipeline-template.yml \
      --stack-name test-data-visualizer-pipeline \
      --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
      --no-fail-on-empty-changeset
