name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy-test:
    name: Deploy to Test Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Deploy to AWS Test Environment
        run: |
          sam build
          sam deploy --template-file test-pipeline-file.yaml --stack-name test-data-visualizer-test --capabilities CAPABILITY_IAM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1

  deploy-prod:
    name: Deploy to Production Environment
    needs: deploy-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js environment for prod
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies for prod
        run: npm install

      - name: Deploy to AWS Production Environment
        run: |
          sam build
          sam deploy --template-file Prod-Pipeline.yaml --stack-name prod-data-visualizer-live --capabilities CAPABILITY_IAM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1
