name: Deploy to AWS - Testing Pipeline
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: Set SAM CLI Project Root
        run: echo "SAM_CLI_TELEMETRY=0" >> $GITHUB_ENV
      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli
      - name: Deploy to AWS (Testing Environment)
        run: |
          cd Test-Data-Visualizer
          sam build --template-file template.yml
          sam deploy --template-file template.yml --stack-name DataVisualiserTestPipeline --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset
